BEGIN

DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'ETL', TABNAME=>'EMPLOYEE', ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE, CASCADE => TRUE);

END;



---------------------------
SELECT LAST_ANALYZED

FROM ALL_ALL_TABLES 

WHERE TABLE_NAME = 'EMPLOYEE'