CREATE TABLESPACE ETL_DATA DATAFILE 
'/oracle/app/oracle/oradata/ETLTEST/DATA_TBS01.dbf' SIZE 100M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



-- Max Size TABLESPACE 32G
-- If TABLESPACE Full add more file by running

ALTER TABLESPACE ETL_DATA ADD DATAFILE '/oracle/app/oracle/oradata/ETLTEST/DATA_TBS02.dbf' SIZE 100M AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED;


